### PR TITLE
Added option for counter to be centered

### PR DESCRIPTION
**Pull request by dodo721**
Lets the counter use text-center instead of just right align

### CODE REVIEW

**Comment by dodo721** [comment]
Added my changes to the sogive normalisation to this PR, to avoid cluttering up the git with multiple PRs of one line changes

**Comment by winterstein** [comment]
Hello @dodo721 

I tested here - http://localstudio.good-loop.com/#widgets?f=counter - and saw a bit of glitchy layout: The final "0" occasionally being squished into the line below.

**Comment by dodo721** [comment]
Added a fix, should work now!

**Comment by dodo721** [comment]
Done

**Pull request merged**
