### PR TITLE
(reviewing) Listload load separate item for logo so it updates

### PR DESCRIPTION
**Pull request by dodo721**
Pair to PR in adserver of same name

### CODE REVIEW

**Comment by winterstein** [comment]
@dodo721 Hello Vera. What's the use-case for this? Thanks.

**Comment by dodo721** [comment]
@winterstein it's a fix for this ticket:
https://good-loop.monday.com/boards/2603585504/views/60487313/pulses/5085356780?userId=30206527

**Comment by winterstein** [comment]
Thanks @dodo721 

I'm wary of adding lots of extra http requests. That could cause performance issues that are more of a problem than the update issue. 

Hm...

Why doesn't the update appear in the list? If the Advert object has been changed in memory (i.e. in DataStore), why does ListLoad show older data? Is DataStore.resolveDataList() being called (and if not - would that fix it)?

**Comment by dodo721** [comment]
Not directly - the logo is being set from the advert's own branding object in the original code, which seems to be set to the advertiser's logo at creation, though I was unable to find exactly where this takes place. As it's saved in the advert though, the original code has no way to know it's really looking for a vertiser logo so doesn't update - I was also wary of more requests, but I can't think of a way to get the logos to update without fetching the advertiser object in some way. getDataItem I thought would fetch the DataStore cached version if it can?

**Comment by roscoemcinerney** [comment]
The Advertiser is fairly likely already getting fetched by a PCDI or similar in this context, so this will probably be a cache hit. I've made an edit to reduce binding between ListLoad and Good-Loop data-item structure, though, where the "fetch secondary item by ID" logic is in an overrideable LogoComponent instead of baked into ListLoad.

**Pull request merged**
