### PR TITLE
fixed bug where caret was being set on every input

### PR DESCRIPTION
**Pull request by LewisFramps**

### CODE REVIEW

**Comment by winterstein** [comment]
Hello Aidan and Lewis

@LewisFramps has done some work adding a new `modal` feature to PropControl. Thanks Lewis.

It looks like most of that has been merged into master already. @Lewis - Is that right?

Since PropControl is used in a lot of places, edits to PropControl need extra care and testing.

@LewisFramps Do we have a few test widgets in studio.good-loop.com? 
If not please add some.

Then let @athomson0 know so he can do some try-to-break-it testing.

Thanks guys,
Dan

**Comment by winterstein** [comment]
NB: I think we can merge this little PR. It's the wider edits that want robust testing.

**Comment by LewisFramps** [comment]
added a few test widgets into studio!
https://github.com/good-loop/studio/pull/5

**Comment by athomson0** [comment]
Still having build errors relating to `prismjs`. Does this work for you @roscoemcinerney?

**Comment by roscoemcinerney** [comment]
Ah, we've got a case of feature creep here. I strongly recommend walking back the addition of syntax highlighting in this PR - this one should just be the self-contained feature of "allow textarea inputs to pop out to make more room to work without messing up the layout flow".

The syntax highlighting is great but let's have a new branch + PR where it's its own PropControl type - let's say PropControlCode.jsx - which can register a few types (eg type="css", type="html", type="js") and import prismjs itself. @LewisFramps Grab me when you want to get started if it's not clear what to do from the other PropControl modules.

**Comment by LewisFramps** [comment]
Removed scope creep, back to just concerning modals & caret position. Adding another branch with syntax-highlighting

**Pull request merged**
